version: "3.6"

services:
  alar_nginx:
    image: alar_front:latest
    container_name: alar_nginx
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/alar.conf
      - ${SITE_PATH}/media:/usr/share/nginx/html/media
      - ${SITE_PATH}/static/admin:/usr/share/nginx/html/static/admin
      - ${SITE_PATH}/static/rest_framework:/usr/share/nginx/html/static/rest_framework
    ports:
      - 80:80
      - 443:443
    depends_on:
      - alar_site
    networks:
      - alar-network

  alar_db:
    image: postgres:11
    container_name: alar_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=alar
    networks:
      - alar-network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

  alar_redis:
    image: redis
    container_name: alar_redis
    networks:
      - alar-network
    expose:
      - "6379"

  alar_site:
    image: alar:latest
    container_name: alar_site
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=alar
      - DB_HOST=alar_db
      - DEBUG=False
    depends_on:
      - alar_db
    networks:
      - alar-network
    volumes:
      - ${SITE_PATH}:/app
    ports:
      - 7991:8000
    command: ./entrypoint.sh

networks:
  alar-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}